server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://hz.aifyun.com:3307/aiyun
    password: 2806573
#显示sql
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置下划线转驼峰
    map-underscore-to-camel-case: true
  #注册Mapper.xml配置文件
  mapper-locations: classpath:mapper/*.xml
#分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#主键方式
mapper:
  identity: MYSQL
auth:
  Login:
    #不拦截的请求 逗号隔开
    NotInterception: "/user/login,/user/registered"